local L = LibStub("AceLocale-3.0"):NewLocale("Click2Cast","enUS",true)
if not L then return end

L["Menu"] = true
L["Spell"] = true
L["Target"] = true
L["Focus"] = true
L["Assist"] = true
L["Macro"] = true
L["Macro Name"] = true
L["None"] = true
L["Spell Name"] = true
L["Macro Text"] = true
L["Macro ID"] = true
L["Macro Name"] = true
L["Enter the name of the spell to cast."] = true
L["Enter the macro code to execute."] = true
L["Enter the name of the macro to execute. Useful for multi-line macros."] = true
L["Enter the ID of the macro to execute. Useful for multi-line macros."] = true
L["Shift"] = true
L["Alt"] = true
L["Ctrl"] = true
L["Control"] = true
L["Click2Cast allows you to bind spells, macros and other actions to mouse clicks and keyboard strokes. For example this allows you to heal and buff your party and raid members easily just by clicking on them."] = true
L["Mouse Bindings"] = true
L["Button"] = true
L["Select binding button."] = true
L["Button 1"] = "Left Mouse"
L["Button 2"] = "Right Mouse"
L["Button 3"] = "Middle Mouse"
L["Button 4"] = "Mouse 4"
L["Button 5"] = "Mouse 5"
L["Button 6"] = "Mouse 6"
L["Button 7"] = "Mouse 7"
L["Button 8"] = "Mouse 8"
L["Button 9"] = "Mouse 9"
L["Button 10"] = "Mouse 10"
L["Button 11"] = "Mouse 11"
L["Button 12"] = "Mouse 12"
L["Button 13"] = "Mouse 13"
L["Button 14"] = "Mouse 14"
L["Button 15"] = "Mouse 15"
L["Modifier 1"] = true
L["Select modifier button."] = true
L["Modifier 2"] = true
L["Create New Binding"] = true
L["Creates a configurable click binding."] = true
L["Keyboard Bindings"] = true
L["Select binding button."] = true
L["Current input is not a valid key binding."] = true
L["Action"] = true
L["Select binding action."] = true
L["Spell Rank"] = true
L["Set spell rank."] = true
L["Outside Unitframes"] = true
L["Allows you to use the mouse click binding everywhere, not just on unit frames."] = true
L["%s(Rank %s)"] = true
L["No Modifier"] = true
L["|cffeda55fRight-Click|r to configure clickcast actions."] = true